### ISSUE TITLE
Correct Media type for N-Quads is application/n-quads, not application/nquads

### ISSUE THREAD

**Issue by jakubklimek** [digitalbazaar/jsonld-cli#16]
Correct Media type for N-Quads is application/n-quads, not application/nquads, which is specified in the code.

**Comment by davidlehn** [comment]
Yeah, that should be updated.  The lib itself used to use that spelling, but it's long since been updated to handle both.

**Comment by VladimirAlexiev** [comment]
:+1: https://www.w3.org/TR/n-quads/#h2_sec-mediaReg

**Comment by BigBlueHat** [comment]
Fixed in https://github.com/digitalbazaar/jsonld-cli/commit/f5312edff553976da16898742f58adece1728510
