### ISSUE TITLE
CURIE not handled in `@vocab`

### ISSUE THREAD

**Issue by VladimirAlexiev** [digitalbazaar/jsonld-cli#18]
https://www.w3.org/TR/json-ld11/#context-definitions says `@vocab` can be a CURIE.

The playground [handles this](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22%40vocab%22%3A%22https%3A%2F%2Fns.gs1.org%2Fepcis%2F%22%2C%22cbv%22%3A%22https%3A%2F%2Fns.gs1.org%2Fcbv%2F%22%2C%22bizStep%22%3A%7B%22%40type%22%3A%22%40vocab%22%2C%22%40context%22%3A%7B%22%40vocab%22%3A%22cbv%3ABizStep-%22%7D%7D%7D%2C%22%40graph%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fexmaple.org%2Fevent%2F1%22%2C%22bizStep%22%3A%22installing%22%7D%7D):
```json
{
  "@context": {
    "@version": 1.1,
    "@vocab" : "https://ns.gs1.org/epcis/",
    "cbv": "https://ns.gs1.org/cbv/",
    "bizStep": {"@type":"@vocab", "@context":{"@vocab":"cbv:BizStep-"}}
  },
  "@graph":{
    "@id":"https://exmaple.org/event/1",
    "bizStep": "installing"
  }
}
```
results in
```ttl
<https://exmaple.org/event/1> <https://ns.gs1.org/epcis/bizStep> <https://ns.gs1.org/cbv/BizStep-installing> .
```

But if you save to a file and try with jsonld-cli, the prefix is not expanded:
```ttl
jsonld format -q jsonld-cli-issue-18.jsonld
<https://exmaple.org/event/1> <https://ns.gs1.org/epcis/bizStep> <cbv:BizStep-installing> .
```

Related to #1, #6 ?
Many other 1.1 features are handled fine.

**Comment by VladimirAlexiev** [comment]
I wonder what'd happen if we change the dependency to `"jsonld": "^5.2.0"`. I've never built a nodejs module so I don't dare.

@jindrichmynarz I guess that stale copy is not used because the playground produces different results? Maybe post a bug against the playground about that stale copy?

**Comment by jindrichmynarz** [comment]
I've tried that before, but upgrading the `jsonld` dependency of jsonld-cli is not that straightforward.

**Comment by BigBlueHat** [comment]
@VladimirAlexiev [v2.0.0 of jsonld-cli supports jsonld.js v8.3.2+](https://github.com/digitalbazaar/jsonld-cli/blob/main/package.json#L36).

Is this still an issue in the current version?

**Comment by VladimirAlexiev** [comment]
It's now fine:
```
<https://exmaple.org/event/1> <https://ns.gs1.org/epcis/bizStep> <https://ns.gs1.org/cbv/BizStep-installing> .
```
Thanks!
